export const dummyData = [
  {
    orderId: 1,
    orderSize: '2',
    name: 'Deebendu',
    city: 'Chandighar',
    orderPrice: 200,
    status: 'Pending',
    orderDate: '2024-03-10',
  },
  {
    orderId: 2,
    orderSize: '2',
    name: 'Rivanshu',
    city: 'Meerut',
    orderPrice: 5000,
    status: 'Delivered',
    orderDate: '2024-03-09',
  },
  {
    orderId: 3,
    orderSize: '2',
    name: 'Lavi',
    city: 'Shamli',
    orderPrice: 300,
    status: 'Pending',
    orderDate: '2024-03-10',
  },
  {
    orderId: 4,
    orderSize: '2',
    name: 'Gurleen',
    city: 'Delhi',
    orderPrice: 150,
    status: 'Delivered',
    orderDate: '2024-03-09',
  },
  {
    orderId: 5,
    orderSize: '2',
    name: 'Aakash',
    city: 'Noida',
    orderPrice: 100,
    status: 'Pending',
    orderDate: '2024-03-10',
  },
  {
    orderId: 6,
    orderSize: '2',
    name: 'Nikhil',
    city: 'Ghaziabad',
    orderPrice: 150,
    status: 'Delivered',
    orderDate: '2024-03-09',
  },
  {
    orderId: 1,
    orderSize: '2',
    name: 'Deebendu',
    city: 'Chandighar',
    orderPrice: 200,
    status: 'Pending',
    orderDate: '2024-03-10',
  },
  {
    orderId: 2,
    orderSize: '2',
    name: 'Rivanshu',
    city: 'Meerut',
    orderPrice: 5000,
    status: 'Delivered',
    orderDate: '2024-03-09',
  },
  {
    orderId: 3,
    orderSize: '2',
    name: 'Lavi',
    city: 'Shamli',
    orderPrice: 300,
    status: 'Pending',
    orderDate: '2024-03-10',
  },
  {
    orderId: 4,
    orderSize: '2',
    name: 'Rivanshu',
    city: 'Meerut',
    orderPrice: 150,
    status: 'Delivered',
    orderDate: '2024-03-09',
  },
  {
    orderId: 5,
    orderSize: '2',
    name: 'Deebendu',
    city: 'Chandighar',
    orderPrice: 100,
    status: 'Pending',
    orderDate: '2024-03-10',
  },
  {
    orderId: 6,
    orderSize: '2',
    name: 'Rivanshu',
    city: 'Meerut',
    orderPrice: 150,
    status: 'Delivered',
    orderDate: '2024-03-09',
  },
];
